### ISSUE TITLE
Attributes missing for mod_shared_roster_ldap

### ISSUE THREAD

**Issue by debalance** [processone/docs.ejabberd.im#8]
Hi,
just noticed that in the "Attributes" section of http://docs.ejabberd.im/admin/guide/configuration/#modsharedrosterldap the attributes are missing/invisible, only their description is there.

Also there are lines like
*posixGroup \(\rightarrow{}\) memberUid*
that should be corrected for the new format.

**Comment by prefiks** [comment]
Thank you for spotting this. Commit 42464eefd35154c6c35762318ca4ed10e4b90a08 should fix this. Version on docs.ejabberd.im should be updated on next run of updater script cron job.

**Comment by mremond** [comment]
It should now be deployed. Thanks !

**Comment by debalance** [comment]
That only fixed part of it, the attributes whose descriptions are there are still missing, which makes the descriptions pretty useless.

The attributes are:
ldap_groupattr
ldap_groupdesc
ldap_memberattr
ldap_userdesc
ldap_useruid

Compare it to this version of the guide:
https://www.process-one.net/docs/ejabberd/guide_en.html#htoc64

Plus the ones in the description now got unnecessary backslashes in them, e.g. ldap\\_groupattr

**Comment by prefiks** [comment]
I commited bd7f125f7c2405830efd29831d82008851bab84c that adds missing field names, and improves some other formating issues in this file.

**Comment by mremond** [comment]
It is now deployed. Is that ok now ?

**Comment by prefiks** [comment]
Looks correct to me

**Comment by mremond** [comment]
Thanks !
